// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACuk9GHZWZ9lZkFRklNLVZpmjiBCDDTdE',
    appId: '1:345153981257:web:1f50914cb5e744e80e6898',
    messagingSenderId: '345153981257',
    projectId: 'beauty-app-e09a8',
    authDomain: 'beauty-app-e09a8.firebaseapp.com',
    storageBucket: 'beauty-app-e09a8.appspot.com',
    measurementId: 'G-6KJVK1Z02B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACdv0ODo0BaTKH_oHSOSNnSkRnKJD-0qc',
    appId: '1:345153981257:android:18d6b441c25ed8020e6898',
    messagingSenderId: '345153981257',
    projectId: 'beauty-app-e09a8',
    storageBucket: 'beauty-app-e09a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaucNVlJV1oeJp6x2W-4KHUb7JYtARVfY',
    appId: '1:345153981257:ios:9c9b816b040346cc0e6898',
    messagingSenderId: '345153981257',
    projectId: 'beauty-app-e09a8',
    storageBucket: 'beauty-app-e09a8.appspot.com',
    iosBundleId: 'com.example.beautyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaucNVlJV1oeJp6x2W-4KHUb7JYtARVfY',
    appId: '1:345153981257:ios:9c9b816b040346cc0e6898',
    messagingSenderId: '345153981257',
    projectId: 'beauty-app-e09a8',
    storageBucket: 'beauty-app-e09a8.appspot.com',
    iosBundleId: 'com.example.beautyapp',
  );
}
